# Site settings
title: Stew Gleadow's Blog
email: sgleadow@gmail.com
description: "My random thoughts about iOS development, backend services and all the associated fun and games."
# baseurl: "/stewgleadow"
url: "http://stewgleadow.com"
twitter_username: stewgleadow
github_username:  sgleadow

# Build settings
markdown: redcarpet
permalink: /blog/:year/:month/:day/:title
exclude: [LICENSE, README.md, Gemfile, Gemfile.lock, .bundle, .git, vendor, serve]

redcarpet:
  extensions: ["fenced_code_blocks"]
highligher: pygments
